### ISSUE TITLE
alertTitle height issue

### ISSUE THREAD

**Issue by MuhammedAlmaz** [JideGuru/rich-alert-dialogs#2]
You have a issue on sweet_alerts_dialog.dart  file at 83. code block .
When I write 2 lines of alertTitle, the ui getting error . I change the `dialogHeight = deviceHeight * (2 / 5);` to `dialogHeight = deviceHeight * (0.45);` and its work but you need solve this issue.

**Comment by JideGuru** [comment]
Hey, thanks for reporting this issue. i've never noticed it before. i will fix it.
Thanks
